[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:midirouter]
command=node /app/server.js
directory=/app
user=midi
autostart=true
autorestart=true
stderr_logfile=/var/log/midirouter.err.log
stdout_logfile=/var/log/midirout.out.log
environment=NODE_ENV="production"
